### ISSUE TITLE
What means...

### ISSUE THREAD

**Issue by baszero** [L3-N0X/spicetify-dj-info#1]
Sorry to ask, but what means Key 2B or Key 10B ?
I'm used to E-minor or G-major etc.

When a track shows E90%, what does this mean?

An explanation somewhere would help. Thanks! Great extension!!!!!!

**Comment by L3-N0X** [comment]
I updated the Readme file, thanks for mentioning!
The E means the Energy of the song in percent, the Key is displayed in the Camelot Notation, which is used by DJs. A new Extension was made by another person, where you can change the notation of the key!
