### ISSUE TITLE
visual bug with comfy theme

### ISSUE THREAD

**Issue by xhuriken** [L3-N0X/spicetify-dj-info#17]
With the comfy theme:
![image](https://github.com/L3-N0X/spicetify-dj-info/assets/73635763/3b8e769d-b96c-4e7a-abb3-1b7e3a829882)
![image](https://github.com/L3-N0X/spicetify-dj-info/assets/73635763/8eef511a-7cbe-4563-b61f-19019afdf4ee)
With basic theme it's work well

**Comment by L3-N0X** [comment]
Fixed in #19
