### ISSUE TITLE
No visual changes are applied

### ISSUE THREAD

**Issue by terdinatore** [L3-N0X/spicetify-dj-info#18]
Hi L3N0X, thank you for writing this extension. I have used it successfully in the past, but for some time now it has stopped working for me. Similar to #8. 

With devtools enabled, I can see that the event listener for `songchange` is working, but the MutationObservers don't seem to function, at least the breakpoint I put in the code are never triggered. 

Could you help me figure this out?

Config:
> Spotify for macOS (Intel)
> 1.2.37.701.ge66eb7bc
> Spicetify v2.36.11
> Theme: marketplace
> Extensions: djinfo.js
> Custom apps: marketplace
> xpui_2024-05-03_1714757530304_e66eb7b
> cef_122.1.13+gde5b724+chromium-122.0.6261.130
> Runtime: Chrome
> Build System: CMake

**Comment by ppkozlowski** [comment]
I had the same issue. Workaround for me was to clear localstorage in Spotify (Developer Tools -> Application -> Local Storage -> Clear

**Comment by terdinatore** [comment]
> I had the same issue. Workaround for me was to clear localstorage in Spotify (Developer Tools -> Application -> Local Storage -> Clear

Hi @ppkozlowski, thank you for your suggestion. Unfortunately, deleting LS did not help. I also deleted Spotify as well as all its setting files and installed only spicetify-cli and djinfo.js. Still no visual changes, settings are there.

**Comment by L3-N0X** [comment]
Can you please check if #19 fixed this problem? I was not able to reproduce this problem. 
When there is still no information visible, is there a empty space created for the info? Or is there not even a column for the djinfo?

**Comment by terdinatore** [comment]
Hi L3-NOX, to be honest, I stopped tracking the issue on my Spotify app and some time ago (way before you merged #19), after a Spotify version change (and Spicetify too) your extension started to work again. 

Unfortunately, I’ve no idea what made the difference between not displaying the stats and now displaying them. 

Thanks, for checking in though.
