### ISSUE TITLE
Track Info only displaying for some of the tracks in discography

### ISSUE THREAD

**Issue by ioj4** [L3-N0X/spicetify-dj-info#2]
When viewing the discography of an artist only the tracks of the first element get patched
![image](https://user-images.githubusercontent.com/69911332/221688445-f20b0e3c-49e5-4d37-af4c-53347b8def7a.png)

Thx for the great work btw. I use your extension a lot :D

**Comment by L3-N0X** [comment]
I finally found time to update the extension and changed this, so now the discography should be patched right. But there is still a weird bug I can't get fixed. After a few Entries, it just stops and doesn't display any further information for the songs, just the column header are working, and I don't know why. So, if somebody finds what is causing this issue, please let me know!
