### ISSUE TITLE
Thank you, it's okay to close this question, I found that I can't close it

### ISSUE THREAD

**Issue by youthyan** [L3-N0X/spicetify-dj-info#3]
I asked two people and no one was willing to help me. I learned js by myself, I have already learned it, and I can write it myself.

**Comment by L3-N0X** [comment]
I'm sorry, but i don't think I can help you. To display the Info for each track, I used another extension as a base and modified it for my needs. But if you want to just change the text from "Key: ..." to the Artist Info, you have to find the line where the cell is built and where the spotify api request is for the information.

**Comment by youthyan** [comment]
<img width="975" alt="截屏2023-05-01 下午4 00 22" src="https://user-images.githubusercontent.com/105373147/235426496-1e33df1e-3904-426f-9d20-cbc92c6996e0.png">
<img width="375" alt="截屏2023-05-01 下午4 02 51" src="https://user-images.githubusercontent.com/105373147/235426525-3a60cd2d-3d79-41be-b7d9-643e6a7e4f6e.png">
<img width="368" alt="截屏2023-05-01 下午4 02 14" src="https://user-images.githubusercontent.com/105373147/235426532-f4e058d2-1cc7-4fda-af55-f47fcffc31b9.png">
This is the artist's api, but the uri of the artist and audio-features is not the same, 
I only modify it to the artist's api and ${res.name} it is not working

**Comment by youthyan** [comment]
I will modify the css style, but I will not modify the js

**Comment by L3-N0X** [comment]
You have to look exactly, where in the response json name stands. I think, since there can be multiple Artists, each of them has a name and you have to do something like res[0].name, but I'm not 100% sure, I don't know much about programming

**Comment by youthyan** [comment]
I think the extension you wrote is awesome, knowing how to modify it to work,
 I think you can make a new extension that only adds artists, and release it on the market.
 I would think that would be really cool and a lot of people would love it.

**Comment by youthyan** [comment]
You can modify it directly through this extension, you can refer to
The extension js of this genre, which uses the artist's api, the genre and the artist name are the same api  


<img width="392" alt="截屏2023-05-01 下午4 31 16" src="https://user-images.githubusercontent.com/105373147/235429303-5efba82d-3c10-46e9-b39e-09bc5e67ba0d.png">

//This is the js extension of the genre, which can be run directly, using the artist's api. they are the same api
 <reference path="./globals.d.ts" />

(function Genre() {
  const { CosmosAsync, Player } = Spicetify;

  /**
   * Fetch genre from artist
   *
   * @param artistURI {string}
   * @return {Promise<Array>}
   */
  const fetchGenres = async (artistURI) => {
    const res = await CosmosAsync.get(`https://api.spotify.com/v1/artists/${artistURI}`);
    // noinspection JSUnresolvedVariable
    return res.genres.slice(0, 3) // Only keep the first 3 genres
  };

  /**
   * Fetch playlist from The Sound of Spotify for a given genre
   * @param {String} genre
   * @return {String|null}
   */
  const fetchSoundOfSpotifyPlaylist = async (genre) => {
    const query = encodeURIComponent(`The Sound of ${genre}`);
    // Check localStorage for playlist
    const cached = localStorage.getItem(`everynoise:${query}`);
    if (cached !== null) {
      return cached; 
    }

    // Search for playlist and check results for the everynoise account
    const re = new RegExp(`^the sound of ${genre.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'i');
    const res = await CosmosAsync.get(`https://api.spotify.com/v1/search?q=${query}&type=playlist`)
    for (const item of res.playlists.items) {
      if (item.owner.id === "thesoundsofspotify" && re.test(item.name)) {
        localStorage.setItem(`everynoise:${genre}`, item.uri);
        return item.uri
      }
    }
    return null;
  };


  // Store the current playback id
  let playback = null;

  /**
   *
   * @type {Node}
   */
  let genreContainer = null;

  let infoContainer = document.querySelector('div.main-trackInfo-container');

  /**
   * Remove genre injection in the UI
   */
  const cleanInjection = () => {
    if (genreContainer !== null) {
      try {
        infoContainer.removeChild(genreContainer);
      } catch (e) {}
    }
  };

  /**
   * Inject genres to UI
   */
  const inject = () => {
    Player.addEventListener('onprogress', async () => {
      if (Player.data?.track.metadata.hasOwnProperty('artist_uri')) {
        // If the registered song isn't the same as the one currently being played then fetch genres
        if (playback !== Player.data.playback_id) {
          // Save the new track
          playback = Player.data.playback_id;
          const id = Player.data.track.metadata.artist_uri.split(':')[2];
          const genres = await fetchGenres(id);

          cleanInjection();

          genreContainer = document.createElement('div');
          // noinspection JSUndefinedPropertyAssignment
          genreContainer.className = 'main-trackInfo-genres ellipsis-one-line main-type-finale';
          // noinspection JSUnresolvedVariable
          genreContainer.style.color = 'var(--spice-extratext)';

          for (const i in genres) {
            let element;
            const uri = await fetchSoundOfSpotifyPlaylist(genres[i]);
            if (uri !== null) {
              element = document.createElement('a');
              element.innerHTML = genres[i];
              element.href = uri;
            } else {
              element = document.createElement('span');
            }
            element.innerHTML = genres[i];
            element.style.fontSize ="11px";
            element.style.textTransform = "capitalize";
            genreContainer.appendChild(element);
            if (i < genres.length-1) {
              const separator = document.createElement('span');
              separator.innerHTML = ', ';
              genreContainer.appendChild(separator);
            }
          }

          infoContainer = document.querySelector('div.main-trackInfo-container');
          if(!infoContainer) cleanInjection();
          infoContainer.appendChild(genreContainer);

        }
      } else {
        cleanInjection();
      }
    });
  };

  if (!CosmosAsync) {
    setTimeout(Genre, 500);
  } else {
    inject();
  }
})();

**Comment by youthyan** [comment]
//Here is the artist's api link
https://developer.spotify.com/documentation/web-api/reference/get-an-artist
