### ISSUE TITLE
Add-on doesn't work in playlists anymore.

### ISSUE THREAD

**Issue by rosgr100** [L3-N0X/spicetify-dj-info#5]
Seems like after the new update the track info are not displayed in playlists.

**Comment by L3-N0X** [comment]
I don't have this problem right now, as soon as It won't work for me any more of as soon as somebody else can confirm, that it doesn't work anymore, I'll try to fix it

**Comment by rosgr100** [comment]
I only face the problem in playlists. Information are available everywhere else.

![Screenshot 2023-07-21 211009](https://github.com/L3-N0X/spicetify-dj-info/assets/74199552/80a57389-bd55-4df0-a4a1-027acb6c90a0)

![Screenshot 2023-07-21 210935](https://github.com/L3-N0X/spicetify-dj-info/assets/74199552/b7ced5cb-ffb2-4a2d-96af-459b1c5f418c)

**Comment by L3-N0X** [comment]
Fixed in the newest commit! Thanks for opening an issue!
